/* Pokedex Kanto — 151 Pokemon con tipos, rareza y poder.
   Cada entrada minima: id, nombre, tipo principal, rareza, poder. */

export interface KantoEntry {
  id: number
  name: string
  type: string
  rarity: Rarity
  power: number
}

export type Rarity = 'comun' | 'raro' | 'epico' | 'legendario'

export const RARITY_ORDER: Rarity[] = ['comun', 'raro', 'epico', 'legendario']

export const RARITY_LABEL: Record<Rarity, string> = {
  comun: 'Comun',
  raro: 'Raro',
  epico: 'Epico',
  legendario: 'Legendario',
}

export const RARITY_MULT: Record<Rarity, number> = {
  comun: 1,
  raro: 1.5,
  epico: 2.2,
  legendario: 3,
}

export const TYPE_COLOR: Record<string, string> = {
  normal: '#A8A878',
  fire: '#F08030',
  water: '#6890F0',
  electric: '#F8D030',
  grass: '#78C850',
  ice: '#98D8D8',
  fighting: '#C03028',
  poison: '#A040A0',
  ground: '#E0C068',
  flying: '#A890F0',
  psychic: '#F85888',
  bug: '#A8B820',
  rock: '#B8A038',
  ghost: '#705898',
  dragon: '#7038F8',
  steel: '#B8B8D0',
  fairy: '#EE99AC',
}

export const KANTO: KantoEntry[] = [
  { id: 1, name: 'Bulbasaur', type: 'grass', rarity: 'comun', power: 318 },
  { id: 2, name: 'Ivysaur', type: 'grass', rarity: 'raro', power: 405 },
  { id: 3, name: 'Venusaur', type: 'grass', rarity: 'epico', power: 525 },
  { id: 4, name: 'Charmander', type: 'fire', rarity: 'comun', power: 309 },
  { id: 5, name: 'Charmeleon', type: 'fire', rarity: 'raro', power: 405 },
  { id: 6, name: 'Charizard', type: 'fire', rarity: 'epico', power: 534 },
  { id: 7, name: 'Squirtle', type: 'water', rarity: 'comun', power: 314 },
  { id: 8, name: 'Wartortle', type: 'water', rarity: 'raro', power: 405 },
  { id: 9, name: 'Blastoise', type: 'water', rarity: 'epico', power: 530 },
  { id: 10, name: 'Caterpie', type: 'bug', rarity: 'comun', power: 195 },
  { id: 11, name: 'Metapod', type: 'bug', rarity: 'comun', power: 205 },
  { id: 12, name: 'Butterfree', type: 'bug', rarity: 'raro', power: 395 },
  { id: 13, name: 'Weedle', type: 'bug', rarity: 'comun', power: 195 },
  { id: 14, name: 'Kakuna', type: 'bug', rarity: 'comun', power: 205 },
  { id: 15, name: 'Beedrill', type: 'bug', rarity: 'raro', power: 395 },
  { id: 16, name: 'Pidgey', type: 'normal', rarity: 'comun', power: 251 },
  { id: 17, name: 'Pidgeotto', type: 'normal', rarity: 'raro', power: 349 },
  { id: 18, name: 'Pidgeot', type: 'normal', rarity: 'raro', power: 479 },
  { id: 19, name: 'Rattata', type: 'normal', rarity: 'comun', power: 253 },
  { id: 20, name: 'Raticate', type: 'normal', rarity: 'comun', power: 413 },
  { id: 21, name: 'Spearow', type: 'normal', rarity: 'comun', power: 262 },
  { id: 22, name: 'Fearow', type: 'normal', rarity: 'raro', power: 442 },
  { id: 23, name: 'Ekans', type: 'poison', rarity: 'comun', power: 288 },
  { id: 24, name: 'Arbok', type: 'poison', rarity: 'raro', power: 448 },
  { id: 25, name: 'Pikachu', type: 'electric', rarity: 'comun', power: 320 },
  { id: 26, name: 'Raichu', type: 'electric', rarity: 'raro', power: 485 },
  { id: 27, name: 'Sandshrew', type: 'ground', rarity: 'comun', power: 300 },
  { id: 28, name: 'Sandslash', type: 'ground', rarity: 'raro', power: 450 },
  { id: 29, name: 'Nidoran♀', type: 'poison', rarity: 'comun', power: 275 },
  { id: 30, name: 'Nidorina', type: 'poison', rarity: 'raro', power: 365 },
  { id: 31, name: 'Nidoqueen', type: 'poison', rarity: 'epico', power: 505 },
  { id: 32, name: 'Nidoran♂', type: 'poison', rarity: 'comun', power: 273 },
  { id: 33, name: 'Nidorino', type: 'poison', rarity: 'raro', power: 365 },
  { id: 34, name: 'Nidoking', type: 'poison', rarity: 'epico', power: 505 },
  { id: 35, name: 'Clefairy', type: 'fairy', rarity: 'raro', power: 323 },
  { id: 36, name: 'Clefable', type: 'fairy', rarity: 'raro', power: 483 },
  { id: 37, name: 'Vulpix', type: 'fire', rarity: 'comun', power: 299 },
  { id: 38, name: 'Ninetales', type: 'fire', rarity: 'raro', power: 505 },
  { id: 39, name: 'Jigglypuff', type: 'fairy', rarity: 'comun', power: 270 },
  { id: 40, name: 'Wigglytuff', type: 'fairy', rarity: 'raro', power: 435 },
  { id: 41, name: 'Zubat', type: 'poison', rarity: 'comun', power: 245 },
  { id: 42, name: 'Golbat', type: 'poison', rarity: 'raro', power: 455 },
  { id: 43, name: 'Oddish', type: 'grass', rarity: 'comun', power: 320 },
  { id: 44, name: 'Gloom', type: 'grass', rarity: 'raro', power: 395 },
  { id: 45, name: 'Vileplume', type: 'grass', rarity: 'raro', power: 490 },
  { id: 46, name: 'Paras', type: 'bug', rarity: 'comun', power: 285 },
  { id: 47, name: 'Parasect', type: 'bug', rarity: 'raro', power: 405 },
  { id: 48, name: 'Venonat', type: 'bug', rarity: 'comun', power: 305 },
  { id: 49, name: 'Venomoth', type: 'bug', rarity: 'raro', power: 450 },
  { id: 50, name: 'Diglett', type: 'ground', rarity: 'comun', power: 265 },
  { id: 51, name: 'Dugtrio', type: 'ground', rarity: 'raro', power: 425 },
  { id: 52, name: 'Meowth', type: 'normal', rarity: 'comun', power: 290 },
  { id: 53, name: 'Persian', type: 'normal', rarity: 'raro', power: 440 },
  { id: 54, name: 'Psyduck', type: 'water', rarity: 'comun', power: 320 },
  { id: 55, name: 'Golduck', type: 'water', rarity: 'raro', power: 500 },
  { id: 56, name: 'Mankey', type: 'fighting', rarity: 'comun', power: 305 },
  { id: 57, name: 'Primeape', type: 'fighting', rarity: 'raro', power: 455 },
  { id: 58, name: 'Growlithe', type: 'fire', rarity: 'comun', power: 350 },
  { id: 59, name: 'Arcanine', type: 'fire', rarity: 'epico', power: 555 },
  { id: 60, name: 'Poliwag', type: 'water', rarity: 'comun', power: 300 },
  { id: 61, name: 'Poliwhirl', type: 'water', rarity: 'raro', power: 385 },
  { id: 62, name: 'Poliwrath', type: 'water', rarity: 'raro', power: 510 },
  { id: 63, name: 'Abra', type: 'psychic', rarity: 'comun', power: 310 },
  { id: 64, name: 'Kadabra', type: 'psychic', rarity: 'raro', power: 400 },
  { id: 65, name: 'Alakazam', type: 'psychic', rarity: 'epico', power: 500 },
  { id: 66, name: 'Machop', type: 'fighting', rarity: 'comun', power: 305 },
  { id: 67, name: 'Machoke', type: 'fighting', rarity: 'raro', power: 405 },
  { id: 68, name: 'Machamp', type: 'fighting', rarity: 'epico', power: 505 },
  { id: 69, name: 'Bellsprout', type: 'grass', rarity: 'comun', power: 300 },
  { id: 70, name: 'Weepinbell', type: 'grass', rarity: 'raro', power: 390 },
  { id: 71, name: 'Victreebel', type: 'grass', rarity: 'raro', power: 490 },
  { id: 72, name: 'Tentacool', type: 'water', rarity: 'comun', power: 335 },
  { id: 73, name: 'Tentacruel', type: 'water', rarity: 'raro', power: 515 },
  { id: 74, name: 'Geodude', type: 'rock', rarity: 'comun', power: 300 },
  { id: 75, name: 'Graveler', type: 'rock', rarity: 'raro', power: 390 },
  { id: 76, name: 'Golem', type: 'rock', rarity: 'raro', power: 495 },
  { id: 77, name: 'Ponyta', type: 'fire', rarity: 'comun', power: 410 },
  { id: 78, name: 'Rapidash', type: 'fire', rarity: 'raro', power: 500 },
  { id: 79, name: 'Slowpoke', type: 'water', rarity: 'comun', power: 315 },
  { id: 80, name: 'Slowbro', type: 'water', rarity: 'raro', power: 490 },
  { id: 81, name: 'Magnemite', type: 'electric', rarity: 'comun', power: 325 },
  { id: 82, name: 'Magneton', type: 'electric', rarity: 'raro', power: 465 },
  { id: 83, name: "Farfetch'd", type: 'normal', rarity: 'raro', power: 377 },
  { id: 84, name: 'Doduo', type: 'normal', rarity: 'comun', power: 310 },
  { id: 85, name: 'Dodrio', type: 'normal', rarity: 'raro', power: 470 },
  { id: 86, name: 'Seel', type: 'water', rarity: 'comun', power: 325 },
  { id: 87, name: 'Dewgong', type: 'water', rarity: 'raro', power: 475 },
  { id: 88, name: 'Grimer', type: 'poison', rarity: 'comun', power: 325 },
  { id: 89, name: 'Muk', type: 'poison', rarity: 'raro', power: 500 },
  { id: 90, name: 'Shellder', type: 'water', rarity: 'comun', power: 305 },
  { id: 91, name: 'Cloyster', type: 'water', rarity: 'raro', power: 525 },
  { id: 92, name: 'Gastly', type: 'ghost', rarity: 'comun', power: 310 },
  { id: 93, name: 'Haunter', type: 'ghost', rarity: 'raro', power: 405 },
  { id: 94, name: 'Gengar', type: 'ghost', rarity: 'epico', power: 500 },
  { id: 95, name: 'Onix', type: 'rock', rarity: 'raro', power: 385 },
  { id: 96, name: 'Drowzee', type: 'psychic', rarity: 'comun', power: 328 },
  { id: 97, name: 'Hypno', type: 'psychic', rarity: 'raro', power: 483 },
  { id: 98, name: 'Krabby', type: 'water', rarity: 'comun', power: 325 },
  { id: 99, name: 'Kingler', type: 'water', rarity: 'raro', power: 475 },
  { id: 100, name: 'Voltorb', type: 'electric', rarity: 'comun', power: 330 },
  { id: 101, name: 'Electrode', type: 'electric', rarity: 'raro', power: 490 },
  { id: 102, name: 'Exeggcute', type: 'grass', rarity: 'comun', power: 325 },
  { id: 103, name: 'Exeggutor', type: 'grass', rarity: 'raro', power: 530 },
  { id: 104, name: 'Cubone', type: 'ground', rarity: 'comun', power: 320 },
  { id: 105, name: 'Marowak', type: 'ground', rarity: 'raro', power: 425 },
  { id: 106, name: 'Hitmonlee', type: 'fighting', rarity: 'raro', power: 455 },
  { id: 107, name: 'Hitmonchan', type: 'fighting', rarity: 'raro', power: 455 },
  { id: 108, name: 'Lickitung', type: 'normal', rarity: 'raro', power: 385 },
  { id: 109, name: 'Koffing', type: 'poison', rarity: 'comun', power: 340 },
  { id: 110, name: 'Weezing', type: 'poison', rarity: 'raro', power: 490 },
  { id: 111, name: 'Rhyhorn', type: 'ground', rarity: 'comun', power: 345 },
  { id: 112, name: 'Rhydon', type: 'ground', rarity: 'raro', power: 485 },
  { id: 113, name: 'Chansey', type: 'normal', rarity: 'raro', power: 450 },
  { id: 114, name: 'Tangela', type: 'grass', rarity: 'raro', power: 435 },
  { id: 115, name: 'Kangaskhan', type: 'normal', rarity: 'raro', power: 490 },
  { id: 116, name: 'Horsea', type: 'water', rarity: 'comun', power: 295 },
  { id: 117, name: 'Seadra', type: 'water', rarity: 'raro', power: 440 },
  { id: 118, name: 'Goldeen', type: 'water', rarity: 'comun', power: 320 },
  { id: 119, name: 'Seaking', type: 'water', rarity: 'raro', power: 450 },
  { id: 120, name: 'Staryu', type: 'water', rarity: 'comun', power: 340 },
  { id: 121, name: 'Starmie', type: 'water', rarity: 'raro', power: 520 },
  { id: 122, name: 'Mr. Mime', type: 'psychic', rarity: 'raro', power: 460 },
  { id: 123, name: 'Scyther', type: 'bug', rarity: 'raro', power: 500 },
  { id: 124, name: 'Jynx', type: 'ice', rarity: 'raro', power: 455 },
  { id: 125, name: 'Electabuzz', type: 'electric', rarity: 'raro', power: 490 },
  { id: 126, name: 'Magmar', type: 'fire', rarity: 'raro', power: 495 },
  { id: 127, name: 'Pinsir', type: 'bug', rarity: 'raro', power: 500 },
  { id: 128, name: 'Tauros', type: 'normal', rarity: 'raro', power: 490 },
  { id: 129, name: 'Magikarp', type: 'water', rarity: 'comun', power: 200 },
  { id: 130, name: 'Gyarados', type: 'water', rarity: 'epico', power: 540 },
  { id: 131, name: 'Lapras', type: 'water', rarity: 'epico', power: 535 },
  { id: 132, name: 'Ditto', type: 'normal', rarity: 'raro', power: 288 },
  { id: 133, name: 'Eevee', type: 'normal', rarity: 'comun', power: 325 },
  { id: 134, name: 'Vaporeon', type: 'water', rarity: 'epico', power: 525 },
  { id: 135, name: 'Jolteon', type: 'electric', rarity: 'epico', power: 525 },
  { id: 136, name: 'Flareon', type: 'fire', rarity: 'epico', power: 525 },
  { id: 137, name: 'Porygon', type: 'normal', rarity: 'raro', power: 395 },
  { id: 138, name: 'Omanyte', type: 'rock', rarity: 'raro', power: 355 },
  { id: 139, name: 'Omastar', type: 'rock', rarity: 'raro', power: 495 },
  { id: 140, name: 'Kabuto', type: 'rock', rarity: 'raro', power: 355 },
  { id: 141, name: 'Kabutops', type: 'rock', rarity: 'raro', power: 495 },
  { id: 142, name: 'Aerodactyl', type: 'rock', rarity: 'epico', power: 515 },
  { id: 143, name: 'Snorlax', type: 'normal', rarity: 'epico', power: 540 },
  { id: 144, name: 'Articuno', type: 'ice', rarity: 'legendario', power: 580 },
  { id: 145, name: 'Zapdos', type: 'electric', rarity: 'legendario', power: 580 },
  { id: 146, name: 'Moltres', type: 'fire', rarity: 'legendario', power: 580 },
  { id: 147, name: 'Dratini', type: 'dragon', rarity: 'raro', power: 300 },
  { id: 148, name: 'Dragonair', type: 'dragon', rarity: 'raro', power: 420 },
  { id: 149, name: 'Dragonite', type: 'dragon', rarity: 'epico', power: 600 },
  { id: 150, name: 'Mewtwo', type: 'psychic', rarity: 'legendario', power: 680 },
  { id: 151, name: 'Mew', type: 'psychic', rarity: 'legendario', power: 600 },
]
